Accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'Accounts'
urlpatterns = [
    url(r'^login/$',auth_views.login,{'template_name': 'Accounts/login.html'},name='login'),
	url(r'^logout/$',auth_views.logout, name='logout', kwargs={'next_page': '/Accounts/login'}),
	url(r'^signup/$', views.signup, name='signup'),
	url(r'^adminsignup/$', views.adminsignup, name='adminsignup'),
	url(r'^profile/(?P<username>\w+)$', views.profile, name='profile'),
	url(r'^profileUpdate/$', views.profileUpdate, name='profileUpdate'),
	url(r'^password/$', views.change_password, name='change_password'),
]

BillDesk/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from Predictions.views import showPredict

urlpatterns = [
    url(r'^admin/', admin.site.urls),
 	url(r'^DashBoard/', include('DashBoard.urls')),
	url(r'^Accounts/', include('Accounts.urls')),
	url(r'^Accounts/', include('Accounts.urls_django_auth')),
	url(r'^adminpanel/', include('adminpanel.urls')),
	url(r'^DashBoard/showPrediction', showPredict),
]

DashBoard/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
app_name = 'DashBoard'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^test/$',views.test,name='test'),
    url(r'^modify/$',views.modify,name='modify'),
    url(r'^add/$',views.add,name='add'),
    url(r'^addinven/$',views.addinven,name='addinven'),
    url(r'^register/$',views.register,name='register'),
    url(r'^placeorder/$',views.placeorder,name='placeorder'),
    url(r'^autocompleteinven/$',views.autocompleteinven,name='autocompleteinven'),
    url(r'^autocompletecusto/$',views.autocompletecusto,name='autocompletecusto'),
    url(r'^confirm/(?P<w_id>[0-9]+)/$',views.confirm,name='confirm'),
	url(r'^adduser/confirm/(?P<w_id>[0-9]+)/$',views.confirm,name='confirm'),
	url(r'^changeData/$',views.changedata,name='changedata'),
]

adminpanel/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
app_name = 'adminpanel'

urlpatterns = [
    url(r'^$',views.index,name='index'),
]

Accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	full_name = models.CharField(max_length=500, blank=False)
	mob_number = models.CharField(max_length=15, blank=False)
	email_id = models.EmailField(max_length=254, null=True, blank=True)
	Authority_AddInventory = models.CharField(max_length=100,default='unchecked')
	Authority_Billing = models.CharField(max_length=100,default='unchecked')
	Authority_Admin = models.CharField(max_length=100,default='unchecked')
	Authority_Customer = models.CharField(max_length=100,default='unchecked')
	store_id = models.CharField(max_length=100,default='')

	def __str__(self):
		return self.user.username+" "+self.Authority_AddInventory+" "+self.Authority_Billing

class Prod_Val(models.Model):
	product_key = models.CharField(max_length=20)
	Profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
	time_rem = models.IntegerField(default=0)
	con_detail = models.CharField(max_length=10)
	is_active = models.BooleanField(default=False)
	gst_in = models.CharField(max_length=15,default='')

	def __str__(self):
		return self.Profile.user.username + " " + self.product_key+" " + str(self.time_rem)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)
	
	
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()

DashBoard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
# Create your models here.

class Inventory(models.Model):
	i_name = models.CharField(max_length=100)
	i_price = models.IntegerField(default=0)

	def __str__(self):
		return self.i_name + " " +str(self.i_price)

	class Meta:
			ordering = ['i_name']

class Customer(models.Model):
	c_name = models.CharField(max_length=100)
	age_group = models.IntegerField()
	village = models.CharField(max_length=20)
	fb_profile = models.CharField(default='',max_length=100)
	phone = models.CharField(max_length=10)
	def __str__(self):
		return self.c_name + " "+str(self.age_group)+" "+self.village

	class Meta:
			ordering = ['c_name']

Accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	full_name = forms.CharField(max_length=100)
	mob_number = forms.CharField(max_length=15)
	email_id = forms.EmailField(max_length=254)
	
	class Meta:
		model = User
		fields = ('full_name', 'username', 'mob_number', 'email_id', 'password1', 'password2')

Accounts/views.py
from django.contrib import admin
from django.contrib import messages
from django.apps import apps
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.core.management import call_command
from importlib import import_module
from django.conf import settings
from django.core.urlresolvers import clear_url_caches
from django.shortcuts import render, redirect
from Accounts.forms import SignUpForm
from .models import Prod_Val, Profile
from django.db import models
import urllib
from datetime import datetime   
import urllib2
from django.utils.translation import ugettext as _


from django.contrib.auth.models import User
import json


def signup(request):
	if request.method == 'POST':
		form = SignUpForm (request.POST )
		if form.is_valid ():
			store_id = request.POST.get('store_id')
			store_pw = request.POST.get ('pass_wrd')
			store_owner = User.objects.filter(username=store_id).first()
			if store_owner is None or not store_owner.check_password(store_pw) :
				print 'Error'
				return render (request, 'Accounts/signup.html', {'form': form,'Error':'Store owner credentials failed !'})
			print 'No Error'
			user = form.save ()
			user.refresh_from_db ()  # load the profile instance created by the signal
			user.profile.full_name = form.cleaned_data.get ('full_name')
			user.profile.mob_number = form.cleaned_data.get ('mob_number')
			user.profile.email_id = form.cleaned_data.get ('email_id')
			user.email = user.profile.email_id
			user.profile.store_id=store_id
			user.save ()
			raw_password = form.cleaned_data.get ('password1')
			user = authenticate (username=user.username, password=raw_password)
			login (request, user)
			return redirect ('/DashBoard/')
		else:
			return render (request, 'Accounts/signup.html', {'form': form})
	else:
		form = SignUpForm ()
	return render (request, 'Accounts/signup.html', {'form': form})


def create_model(name, fields=None, app_label='', module='', options=None, admin_opts=None, createModel=True,
                 register=True):
    """
    Create specified model
    """
    name = str (name)

    class Meta:
        # Using type('Meta', ...) gives a dictproxy error during model creation
        pass

    if app_label:
        # app_label must be set using the Meta inner class
        setattr (Meta, 'managed', createModel)
        setattr (Meta, 'app_label', app_label)

    # Update Meta with any options that were provided
    if options is not None:
        for key, value in options.iteritems ():
            setattr (Meta, key, value)

    # Set up a dictionary to simulate declarations within a class
    attrs = {'__module__': module, 'Meta': Meta}

    # Add in any fields that were provided
    if fields:
        attrs.update (fields)

    # Create the class, which automatically triggers ModelBase processing
    model = type (name, (models.Model,), attrs)

    # Create an Admin class if admin options were provided
    
    if register and admin_opts is not None:
        class Admin (admin.ModelAdmin):
        	pass
        for key, value in admin_opts:
            setattr (Admin, key, value)
        admin.site.register (model, Admin)

    return model


def get_all_attr(n_model,Customer=None,Inventory=None,Billing=None):
    if n_model == 'Billing':
        fields = {
            'saletime': models.DateTimeField(default=datetime.now, blank=True),
            'Customer': models.ForeignKey(Customer,on_delete=models.CASCADE),
            'tot_price': models.IntegerField(default=0)
        }
        meta = {}
        app_label = 'DashBoard'
        return fields, meta, app_label

    elif n_model == 'Inventory':
        fields = {
            'id': models.AutoField (auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            'i_name': models.CharField (max_length=100),
            'i_price': models.IntegerField (default=0),
            'gst_perc': models.IntegerField (default=0),
            'del_flag':models.BooleanField(default=True)
        }
        meta = {'ordering': ['i_name']}
        app_label = 'DashBoard'
        return fields, meta, app_label
    elif n_model == 'Customer':
        fields = {
            'id': models.AutoField (auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            'c_name': models.CharField (max_length=100),
            'age_group': models.IntegerField (),
            'village': models.CharField (max_length=20),
            'phone': models.CharField (max_length=20),
            'gst_in': models.CharField(max_length=15,default=''),
            'del_flag':models.BooleanField(default=True)
        }
        meta = {'ordering': ['c_name']}
        app_label = 'DashBoard'
        return fields, meta, app_label
    elif n_model == 'Bill_Inven':
    	fields = {
            'Inventory': models.ForeignKey(Inventory,on_delete=models.CASCADE),
            'Billing':models.ForeignKey(Billing,on_delete=models.CASCADE),
            'count': models.IntegerField(default=0),
            'price':models.IntegerField(default=0)
        }
        meta = {}
        app_label = 'DashBoard'
        return fields, meta, app_label

def c_store_db(username):
	try:
		f, m, a = get_all_attr ('Inventory')
		Inven = create_model (username+'Inventory', fields=f, module=a + '.models', options=m, app_label=a, admin_opts={})
		f, m, a = get_all_attr ('Customer')
		Custo = create_model (username+'Customer', fields=f, module=a + '.models', options=m, app_label=a, admin_opts={})
		f, m, a = get_all_attr ('Billing',Customer=Custo)
		Bill = create_model (username+'Billing', fields=f, module=a + '.models', options=m, app_label=a, admin_opts={})
		f, m, a = get_all_attr ('Bill_Inven',Inventory=Inven,Billing=Bill)
		create_model (username+'Bill_Inven', fields=f, module=a + '.models', options=m, app_label=a, admin_opts={})
		
		call_command ('makemigrations')
		call_command ('migrate')
		reload (import_module (settings.ROOT_URLCONF))
		clear_url_caches ()
   	except Exception as e:
   		print '\n\n\tTable Not Created !!! due to ' + str(e)
   		return False
   	return True

def get_model(username,n_model):
	return apps.get_model('DashBoard',username+n_model)
	
def adminsignup(request):
    productkeyErrors = ''
    if request.method == 'POST':
        pk = request.POST['productkey']
        form = SignUpForm (request.POST)
        if form.is_valid ():
			if (len (pk) > 0):
			    try:
			        url = 'https://billdesk-auth.000webhostapp.com'
			        post_fields = {'pk': pk}
			        response = urllib2.Request (url, urllib.urlencode (post_fields).encode ())
			        j = json.loads (urllib2.urlopen (response).read ())
			        state = j['state']
			    except:
			        state = -1
			else:
			    state = 0;
			if state == -1:
			    productkeyErrors = 'Error in verifying Product Key, Try Again'
			elif state == 0:
			    productkeyErrors = 'Wrong Product Key'
			elif state == 1:
			    productkeyErrors = 'Key already registered'
			if state != 2:
				return render (request, 'Accounts/adminsignup.html',
			                   {'form': form, 'productkeyErrors': productkeyErrors})
			user = form.save ()
			user.refresh_from_db ()  # load the profile instance created by the signal
			user.profile.full_name = form.cleaned_data.get ('full_name')
			user.profile.mob_number = form.cleaned_data.get ('mob_number')
			user.profile.email_id = form.cleaned_data.get ('email_id')
			user.profile.Authority_Admin = 'checked'
			user.profile.Authority_Billing = 'checked'
			user.profile.Authority_Inventory = 'checked'
			user.profile.Authority_Customer = 'checked'
			user.profile.store_id = user.username
			user.save ()
			c_store_db(user.username)
			P_Val = Prod_Val(product_key=pk,Profile=user.profile,con_detail=user.profile.mob_number)
			P_Val.save()
			raw_password = form.cleaned_data.get ('password1')
			user = authenticate (username=user.username, password=raw_password)
			login (request, user)
			return redirect ('/DashBoard/')
    else:
        form = SignUpForm ()
    return render (request, 'Accounts/adminsignup.html', {'form': form, 'productkeyErrors': productkeyErrors})

def profile(request,username):
	user=User.objects.get(username=username)
	data=Profile.objects.get(user=user)
	return render(request,'Accounts/profile.html',{'data':data})

def profileUpdate(request):
	username=request.user.username
	user=User.objects.get(username=username)
	data=Profile.objects.get(user=user)
	data.full_name=request.POST.get('full_name')
	data.mob_number=request.POST.get('mob_number')
	data.email_id=request.POST.get('email_id')
	data.save()
	return redirect('Accounts:profile', username=request.user.username)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, _('Your password was successfully updated!'))
            return redirect('Accounts:profile',username=request.user.username)
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'Accounts/change_password.html', {
        'form': form
    })

DashBoard/templates/Accounts/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>
</body>
</html>

DashBoard/templates/Accounts/login.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>BillDesk | Login</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		
		<style type="text/css">
			input[type=text] , input[type=password]{
				
				box-sizing: border-box;
				border: 2px solid #ccc;
				border-radius: 4px;
				font-size: 16px;
				background-color: white;
				background-position: 10px 10px; 
				background-repeat: no-repeat;
				padding: 12px 20px 12px 40px;
				-webkit-transition: width 0.4s ease-in-out;
				transition: width 0.4s ease-in-out;
			}
		 </style>
	</head>
	<body>
		<div class="container">
			<br><br>
			<div class="col-md-4 col-md-offset-4 well">
				<center>
					<form method="post" action="/Accounts/login/">
						<h2>Login to BillDesk</h2>
						<br>
						{% if form.errors %}
							<span style="color:RED">Incorrect username/password</span>
							<br><br>
						{% endif %}
						{% csrf_token %}
						
						<input id="id_username" placeholder="Username" autofocus required maxlength="254" name="username" type="text">
						{% if 'username' in form.errors %}
							<span>{{ form.username.errors }}</span>
						{% endif %}
						<br><br>
						<input id="id_password" placeholder="Password" required name="password" type="password">
						{% if 'password' in form.errors %}
							<span>{{ form.password.errors }}</span>
						{% endif %}
						<br><br>
						<button type="submit" value="login">Login</button>
						<input type="hidden" name="next" value="/DashBoard/">
					</form>
					<br>
					<a href="/Accounts/signup/">Don't have an account ? Signup here</a><br/>
					<a href="/Accounts/password_reset/">Forgot Password ></a>
				</center>
			</div>
		</div>
	</body>
</html>

DashBoard/templates/Accounts/profile.html
 {% load staticfiles %}
  <title>BillDesk | Profile</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript">
  </script> <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
  <style type="text/css">

<style type="text/css">
  .list ul li
  {
    display: inline;
    padding: 20px;
    font-size:20px;
  }


  .hed
  {
    margin-left:50px;
  }

  .box{

  border-style:solid;
  border-color:black;
  border-size:1px;
  height:60px;
  width:60px;
  background-color:black;
  }
 .box .glyphicon{

 padding:18px;
  height:30px;
  width:30px;
  }
   .box .fa{

 padding:25px;
  height:30px;
  width:30px;
  }


.back
{

  height:400px;
  width:100%;
  background-size:cover;
}
.img{
margin-bottom:-10px;
margin-top:20px;

}
.round
{
 border-radius:30%;
}
.input-group-addon
{
background-color:black;
color:white;
}

      footer{
    background-color:black;
    height:130px;

    width:100%;
    bottom:0;
    font-weight:lighter;
    color:white;
}
.footerHeader{
    width:100%;
    padding:1em;
    background-color:rgba(52, 73, 94,1.0);
    text-align:center;
    color:white;
}
footer h3{
    font-weight:lighter;
}
footer ul{
    padding-left:5px;
    list-style:none;
}
footer p{
    text-align : justify;
    font-size : 12px;
}
footer iframe {
    width:100%;
    position:relative;
    height:170px;
}
.sm{
    list-style:none;
    overflow:auto;
}
.sm li {
    display: inline;
    padding:5px;
    float:left;
}
.sm li a img {
    width:32px;
}
  /*===========================
  Menu and Navigation
============================
.navbar-brand {
  float: left;
  height: 50px;
  padding: 15px 15px;
  font-size: 18px;
  line-height: 20px;
}

.navbar-brand h1 {
  margin-top:9px;
  padding-top:5px;
  float: left;
  font-size: 25px;
  color:#fff;
  text-transform:uppercase;
  font-weight:600;
}

@media (max-width: 767px) {
  .navbar-brand {
    padding: 0 0 0 15px;
  }
}

.menu {
  font-size:12px;
  float:right;
  text-transform:uppercase;
  font-weight:600;
}

.navbar-collapse {
  padding-right: 15px;
  padding-left: 15px;
  overflow-x: visible;
  -webkit-overflow-scrolling: touch;
  border-top: 0px solid transparent;
  -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, .1);
          box-shadow: inset 0 1px 0 rgba(255, 255, 255, .1);
}
.navbar-collapse.in {
  overflow-y: auto;
}

.menu ul.nav-bar li {
  color:#fff;
}

.nav-bar {
  border-bottom: 0;
}
.nav-bar > li {
  float: left;
  margin-bottom: 0;
}

.nav-bar > li > a {
  border-radius:0;
  color:#fff;
  padding:30px;
}

.nav-bar > li > a:hover {
  color:#272727;
  background:#fff;
}

.nav-bar > li a.active {
  color: #555;
  cursor: default;
  background-color: #fff;
  border: 1px solid #fff;
  border-bottom-color:#fff;
}

.navbar-default {
  background-color: #65AAF0;
  border-color:#65AAF0;
}*/

.bak
{
  background-color: #F2F4F4;
}
.pro
{
  background-color:#FDFEFE ;
   border-size:2px;
   box-shadow: 10px 10px 5px #888888;
   height:100px;
   padding: 20px;
}

  .box:hover
    {
      -moz-transform: scale(1.1);
  -webkit-transform: scale(1.1);
  transform: scale(1.1);
    }
    .nim-menu{
  padding: 10px;
  transition: all 0.8s;
        background-color:black;
        border-bottom:none;
        transition:all 0.4s ease-in;
        -webkit-transition:all 0.4s ease-in;
        -moz-transition:all 0.4s ease-in;
        -ms-transition:all 0.4s ease-in;

}
.navbar
{
  background-color:blue;
}
.nim-menu.navbar-default .navbar-nav > li > a:hover {

  color:black;
  background-color:white;


}
.nim-menu.navbar-default .navbar-nav > li > a{

  color:white;

}
.nav > li a.active {
  color:black;
  background-color:white;

}

.nav > li > a:hover {
  color:white;
  background-color:#65AAF0;
}

    .bak
    {
      background-color: #F2F4F4;
    }
    .lower
    {
     background-color:white;
    }
</style>
<div class="container">
  <h2 class="col-md-12">
      {% if user.is_superuser %}
      <a href="{% url 'adminpanel:index' %}">BillDesk</a>
      {% else %}
      <a href="{% url 'DashBoard:index' %}">BillDesk</a>
      {% endif %}
  {% if user.is_authenticated %}
    <span class="pull-right" align="right">Hi <a href="{% url 'Accounts:profile' user.username %}">{{ user.username }}</a>!  <a href="{% url 'Accounts:logout' %}">[logout]</a></span>
  {% else %}
    <span class="pull-right" align="right">Hi Guest!  <a href="{% url 'Accounts:login' %}">[login]</a></span>
  {% endif %}
  </h2>
          <br/><br/><br/><br/><br/><br/>
      {% if data.user.username == user.username %}
       <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-1">
    <div class="box">
      <center><h3 style="color:white;">U</h3></center>
    </div>
   </div>
   <div class="col-sm-2">
      <strong><p style="margin-top:15px;color:black;font-size:20px;">{{ data.user.username }}</p></strong>
   </div>
       </div>

    <div class="row">
   <div class="col-sm-2">
      <strong><a href="{% url 'Accounts:change_password' %}">Change Password</a></strong>
   </div>
    </div>
    <br/><br/>
    <form action="{% url 'Accounts:profileUpdate' %}" method="Post">
        {% csrf_token %}
          <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"><i class="fa fa-"></i>&nbsp;&nbsp;Full Name</div>
                            <input type="text" class="form-control" name="full_name" id="full_name"  value= "{{ data.full_name }}">
                        </div>
                    </div>
          <br>
          <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"><i class="fa fa-"></i>Mobile Number</div>
                            <input type="text" class="form-control" name="mob_number" id="mob_number" value="{{ data.mob_number }}">
                        </div>
                    </div>
          <br>
          <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"><i class="fa fa-"></i>&nbsp;Email Id</div>
                            <input type="text" class="form-control" name="email_id" id="email_id"  value="{{ data.email_id }}">
                      </div>
                    </div>
                      <button type="submit" name="sub" id="sub"  class="btn btn-primary btn-block bt-login"  data-loading-text="saving In...." style="background-color:black;">SAVE</button>
    </form>
    {%else%}
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-1">
    <div class="box">
      <span class="glyphicon glyphicon-user" style="color:white;"></span>
    </div>
   </div>
   <div class="col-sm-2">
    <strong><p style="margin-top:15px;color:black;font-size:20px;">{{ data.full_name }}</p></strong>
   </div>
   <div class="col-sm-2"></div>
    <div class="col-sm-1">
    <div class="box">
      <span class="glyphicon glyphicon-envelope" style="color:white;"></span>
    </div>
    </div>
    <div class="col-sm-2">
    <strong><p style="margin-top:15px;color:black;font-size:20px;">{{ data.email_id }}</p></strong>
   </div>
   <div class="col-sm-2"></div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-1">
    <div class="box">
      <center><h3 style="color:white;">U</h3></center>
    </div>
   </div>
   <div class="col-sm-2">
      <strong><p style="margin-top:15px;color:black;font-size:20px;">{{ data.user.username }}</p></strong>
   </div>
   <div class="col-sm-2"></div>
    <div class="col-sm-1">
    <div class="box">
      <span class="glyphicon glyphicon-phone" style="color:white;"></span>
    </div>
    </div>
    <div class="col-sm-2">
    <strong><p style="margin-top:15px;color:black;font-size:20px;">{{ data.mob_number }}</p></strong>
   </div>
      {%endif%}
    {% if data.user.is_superuser %}
      {% else %}
    <div class="col-md-12">
        <br><br>
        <pre><b>Store_ID: </b>{{ data.store_id }}</pre>

    </div></div>
    <br>
    <br>
    <br>
    <div class="col-md-12">
        <p><b>Authorities:</b></p><br/>
        {% if data.Authority_AddInventory == 'checked' %}
            <p>Authority_AddInventory</p><br/>
        {% endif %}
        {% if data.Authority_Billing == 'checked' %}
            <p>Authority_Billing</p><br/>
        {% endif %}
        {% if data.Authority_Admin == 'checked' %}
            <p>Authority_Admin</p><br/>
        {% endif %}
        {% if data.Authority_Customer == 'checked' %}
            <p>Authority_Customer</p><br/>
        {% endif %}
    </div>
      {% endif %}
          <br/><br/><br/><br/><br/><br/><br/>
          <br/><br/><br/><br/><br/><br/><br/>
<footer>
    <div class="col-md-5 col-sm-5" >
        <h3>Contact Us</h3>
        <ul>
            <li>Phone : 9923117590 </li>
            <li>E-mail : programtowin@gmail.com</li>
        </ul>
        <p>
            <small>&copy; 2017 BillDesk reserved</small>
        </p>
      </div>
</footer>
</div>